version: '3'

services:
  postgres_mvc:
    image: postgres:9.6.17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prepaid
      POSTGRES_PASSWORD: prepaid
      POSTGRES_DB: prepaid


